sudo: false

language: python

python:
- 3.6

install:
- pip install -r requirements.txt
- pip install pytest-cov
- pip install codecov

script:
- PYTHONPATH=./ pytest --cov=leopard_lavatory

after_success:
- codecov